### ISSUE TITLE
BUG?

### ISSUE THREAD

**Issue by kouzhudong** [zodiacon/PEExplorerV2#2]
![image](https://user-images.githubusercontent.com/18212165/93663472-d7c2d900-fa9a-11ea-98c7-872f75b1067e.png)

**Comment by kouzhudong** [comment]
![image](https://user-images.githubusercontent.com/18212165/93663493-122c7600-fa9b-11ea-8f96-823bf7625d94.png)

**Comment by zodiacon** [comment]
Thanks, will check

**Comment by zodiacon** [comment]
Fixed, thanks!
