### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by kouzhudong** [zodiacon/PEExplorerV2#3]
![image](https://user-images.githubusercontent.com/18212165/93691198-9ec74a80-fb14-11ea-9c07-58224d44685d.png)

**Comment by kouzhudong** [comment]
![image](https://user-images.githubusercontent.com/18212165/93691226-f796e300-fb14-11ea-9e3d-3ff72ded1b9a.png)

**Comment by kouzhudong** [comment]
1>------ 已启动全部重新生成: 项目: PEParser, 配置: Debug x64 ------
1>pch.cpp
1>CLRMetadataParser.cpp
1>PEParser.cpp
1>D:\git\zodiacon\PEExplorerV2\PEParser\PEParser.cpp(153,50): warning C4244: “=”: 从“DWORD”转换到“unsigned short”，可能丢失数据
1>正在生成代码...
1>PEParser.vcxproj -> D:\git\zodiacon\PEExplorerV2\x64\Debug\PEParser.lib
1>已完成生成项目“PEParser.vcxproj”的操作。
2>------ 已启动全部重新生成: 项目: PEExplorerV2, 配置: Debug x64 ------
2>pch.cpp
2>AboutDlg.cpp
2>AssemblyView.cpp
2>ClipboardHelper.cpp
2>DataDirectoriesView.cpp
2>ExportsView.cpp
2>GenericListView.cpp
2>HexView.cpp
2>ImageDosHeaderStruct.cpp
2>ImageFileHeaderStruct.cpp
2>ImageOptionalHeaderStruct.cpp
2>ImportsFrameView.cpp
2>ImportsFunctionsView.cpp
2>ImportsView.cpp
2>MainFrm.cpp
2>ManagedTypesView.cpp
2>PEExplorerV2.cpp
2>PEStrings.cpp
2>ResourcesFrameView.cpp
2>ResourcesView.cpp
2>SectionsView.cpp
2>正在生成代码...
2>正在编译...
2>SortHelper.cpp
2>StructureView.cpp
2>SummaryView.cpp
2>TypeMembersView.cpp
2>正在生成代码...
2>capstone.lib(cs.obj) : 找到 MSIL .netmodule 或使用 /GL 编译的模块；正在使用 /LTCG 重新启动链接；将 /LTCG 添加到链接命令行以改进链接器性能
2>LINK : warning LNK4075: 忽略“/INCREMENTAL”(由于“/LTCG”规范)
2>LINK : fatal error C1900: “P1”(第“20200803”版)和“P2”(第“20190715”版)之间 Il 不匹配
2>LINK : fatal error LNK1257: 代码生成失败
2>已完成生成项目“PEExplorerV2.vcxproj”的操作 - 失败。
========== 全部重新生成: 成功 1 个，失败 1 个，跳过 0 个 ==========

**Comment by zodiacon** [comment]
I messed up.., fixed now!
