### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by morrowd** [zodiacon/PEExplorerV2#5]
Nothing major just a version mismatch between the title bar 2.03 and the about popup 2.02. \

![Version-Mismatch](https://user-images.githubusercontent.com/6360672/93786477-fc32c880-fbf4-11ea-9fc5-893b2e945c47.png)

**Comment by morrowd** [comment]
From the AllTools repo

**Comment by zodiacon** [comment]
Thanks, will fix
