### ISSUE TITLE
Won't compile in Release mode due to a incompatible HexControl library

### ISSUE THREAD

**Issue by gmgallo** [zodiacon/PEExplorerV2#8]
The project compiles fine in Debug x64, but when trying to compile in Release, x64 the linker throus the following fatal error:

2>LINK : fatal error C1047: The object or library file 'HexControl\HexControl.lib' was created by a different version of the compiler than other objects like 'E:\Code\Tools\PEExplorerV2-master\x64\Release\PEParser.lib'; rebuild all objects and libraries with the same compiler

**Comment by zodiacon** [comment]
Yeah, I need to add the source code for the Hex Control so that it compiles with the same compiler.
I recommend you switch to the TotalPE project, which is my "current" PE Viewer project.
